---
  -
    # connector_messages
    connector_messages:
      pg-schema: "public"
      pg-table: "connector_messages"
      attributes:
        - connector
        - entity_type
        - entity_id
        - entity_tax_registration_number
        - payload:
            pg-cast: text
        - created_at
        - updated_at
